# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial sking option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/ober_logo.png"
    alt: ""

### Header
header:
  logo:
    image: "assets/img/jupp_logo.png"
    alt: "M. Jupp"

### Social
social:
  - name: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "www.linkedin.com/in/mjupp/"

### Footer
footer:
  developer: "Developed by <strong>Webistics</strong>"
  copyright: "M. Jupp. All Rights Reserved"

### Portfolio Filters Settings
portfolio:
  filters:
    - name: "Business Dev"
      slug: "business-dev"

    - name: "Product Design"
      slug: "product-design"

    - name: "Academic Research"
      slug: "academic-research"

    - name: "Visual Art"
      slug: "visual-art"
